App\Entity\Product:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~
            - App\Validator\Constraints\DescriptionLength: ~
        price:
            - NotBlank: ~
